### ISSUE TITLE
Putting devCredits, devBanner, devToons(planned) all together in one frontend

### ISSUE THREAD

**Issue by cozyplanes** [Ewpratten/devCredits#20]
Just a random idea. How about putting devSomething collabs into one frontend?
Maybe we can host with devRant.com later time.

**Comment by Ewpratten** [comment]
im fine with that.

**Comment by Ewpratten** [comment]
i own the devrant community github account..... so we could use that.

**Comment by cozyplanes** [comment]
What is the account?

**Comment by Ewpratten** [comment]
Check my new collab. It's a mess because I am tired but it has a link...

**Comment by Ewpratten** [comment]
this is now a thing check devrant-community/unified-frontend repo on github
